### PR TITLE
ARC-enabled

### PR DESCRIPTION
**Pull request by psy2k**
Enabled Automatic Reference Counting and added background controls

### CODE REVIEW

**Comment by muthuka** [comment]
How do I get these updates?

**Comment by psy2k** [comment]
You can get them from my forked Audiostreamer. https://github.com/psy2k/AudioStreamer-ARC

**Comment by muthuka** [comment]
Thank you. I forked and made some other changes. Not sure if that’s useful for you.

Muthu Arumugam
m: 978-495-0931
muthu16@gmail.com

**Comment by mattgallagher** [comment]
Thanks for the offer but in fitting with the "AudioStreamer is badly out-of-date" theme affecting the entire class, I'm going to avoid updating it to ARC. If I ever get back to writing on CocoaWithLove, I might release a completely new audio streaming class using libdispatch and ARC based on code I wrote for a different project. Until then, I'm, going to preserve AudioStreamer as a classic relic of a bygone era when everything was full of bugs and nothing worked quite right.

**Pull request closed without merging**
